
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="rainbowoaks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Rainbow Oaks" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Adds Rainbow Oak trees to your forests.
'''
[[dependencies.rainbowoaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.rainbowoaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"
