
modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="rainbowoaks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Rainbow Oaks" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks to those who commissioned this." #optional
authors="EERussianguy" #optional
description='''
Adds Rainbow Oak trees to your forests.
'''
[[dependencies.rainbowoaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.rainbowoaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    ordering="NONE"
    side="BOTH"
